import { useEffect, useRef, useState } from 'react'
import type { AuthorizedWorkResponse, AuthorizedProjectSummary, ObjectGrant, ScopedReport } from '../../shared/object-access'
import { openTask } from '../navigation'
import { api } from '../api'
import { assignmentAttempt, type SubmissionAttempt } from '../notification-navigation'
import { captureMutationContext } from '../mutation-response'
import { useBusinessResource } from '../use-business-resource'
import { Field, Form, Modal, PageHeader, Badge, nameOf, dateTime, type PageProps } from '../ui'
export default function AuthorizedWork(props:PageProps) {
  const {data}=props, resource=useBusinessResource<AuthorizedWorkResponse>('/authorized-work',`${data.user.id}:${data.operationEpoch}:${data.accessScopeVersion||''}`)
  const [detail,setDetail]=useState<{objectType:string;object:AuthorizedProjectSummary|ScopedReport;capabilities:string[]}|null>(null),[error,setError]=useState('')
  const detailSequence=useRef(0)
  const availableObjects=resource.value?.items.map(item=>item.grantId).join('|')
  useEffect(()=>{detailSequence.current++;setDetail(null);return()=>{detailSequence.current++}},[data.user.id,data.operationEpoch,data.accessScopeVersion,resource.value?.scopeVersion,availableObjects,resource.error])
  return <div><PageHeader title="授权工作" description="仅展示当前账号获授权的对象及范围，授权会在每次读取时重新检查。"/>{resource.error&&<p className="error">{resource.error}</p>}{error&&<p className="error">{error}</p>}
    {!resource.loading&&!resource.value?.items.length&&<p className="note">当前没有可查看的授权对象。</p>}
    {resource.value?.items.map(item=><article className="collaboration-history" key={item.id}><h3>{item.title}</h3><Badge>{item.objectType==='task'?'任务':item.objectType==='project_summary'?'授权范围内的项目摘要':'授权摘要报告'}</Badge><p>{item.capabilities.map(value=>({read:'查看内容',read_evidence:'查看证据',export_summary:'导出摘要'})[value]).join(' · ')}</p><button className="button secondary" onClick={async()=>{const sequence=++detailSequence.current;setDetail(null);setError('');if(item.objectType==='task'){openTask({taskId:item.objectId});return}try{const context=captureMutationContext();const result=await api<{objectType:string;object:AuthorizedProjectSummary|ScopedReport;capabilities:string[]}>(`/authorized-work/${encodeURIComponent(item.grantId)}`);if(sequence===detailSequence.current&&context===captureMutationContext())setDetail(result)}catch(e){if(sequence===detailSequence.current)setError(e instanceof Error?e.message:'读取失败')}}}>查看授权对象</button></article>)}
    {data.user.role==='manager'&&<GrantManagement {...props}/>}
    {detail&&<Modal wide title={'title' in detail.object?detail.object.title:detail.object.name} onClose={()=>{detailSequence.current++;setDetail(null)}}>{detail.objectType==='scoped_report'?<><p className="preserve-lines">{(detail.object as ScopedReport).narrative}</p><p>定稿于 {dateTime((detail.object as ScopedReport).finalizedAt)}</p>{detail.capabilities.includes('export_summary')&&<a className="button secondary" href={`/api/scoped-reports/${detail.object.id}/export`}>下载授权摘要</a>}</>:<p>授权范围内：任务 {(detail.object as AuthorizedProjectSummary).taskCount} 项；自报完成 {(detail.object as AuthorizedProjectSummary).completedTaskCount} 项；受阻 {(detail.object as AuthorizedProjectSummary).blockedTaskCount} 项。</p>}</Modal>}
  </div>
}
export function GrantManagement({data,refresh}:PageProps) {
  const resource=useBusinessResource<{items:ObjectGrant[]}>('/object-grants',`${data.user.id}:${data.operationEpoch}`)
  const reportResource=useBusinessResource<{items:ScopedReport[]}>('/scoped-reports',`${data.user.id}:${data.operationEpoch}`)
  const reportAttempt=useRef<SubmissionAttempt|null>(null)
  const [subjectId,setSubjectId]=useState(''),[objectType,setObjectType]=useState<'task'|'project_summary'|'scoped_report'>('task'),[objectId,setObjectId]=useState(''),[reports,setReports]=useState<ScopedReport[]>([]),[reportError,setReportError]=useState('')
  const reportOptions=[...new Map([...(reportResource.value?.items||[]),...reports].map(r=>[r.id,r])).values()]
  const objects=objectType==='task'?data.tasks.map(t=>({id:t.id,title:t.title,version:t.version})):objectType==='project_summary'?data.projects.map(p=>({id:p.id,title:p.name,version:p.version})):reportOptions
  const selected=objects.find(o=>o.id===objectId),existing=resource.value?.items.find(g=>g.subjectId===subjectId&&g.objectId===objectId&&g.objectType===objectType)
  return <section className="panel grant-management"><h2>对象授权管理</h2>{resource.error&&<p className="error">{resource.error}</p>}<p>任务授权不扩展到整个项目、反馈、绩效或其他成员草稿。当前状态可能已包含历史事实；更早周记录和交付版本只有选择全部历史才可读取。</p>
    <Form submitLabel={existing?.revokedAt?'重新授予对象访问':existing?'更新已有授权':'授予对象访问'} onSubmit={async e=>{const f=new FormData(e.currentTarget);if(!selected)throw new Error('请选择授权对象');await resource.mutate('/object-grants',{subjectId,objectType,objectId,objectVersion:selected.version,capabilities:['read',...f.getAll('capabilities')],historyPolicy:f.get('historyPolicy'),reason:f.get('reason'),expiresAt:f.get('expiresAt')?new Date(`${f.get('expiresAt')}:00+08:00`).toISOString():null,...(existing?{version:existing.version}:{})},refresh)}}>
      <Field label="接收人"><select required value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">请选择账号</option>{data.users.filter(u=>u.active&&u.role==='observer').map(u=><option key={u.id} value={u.id}>{u.name}（{u.role==='observer'?'观察者':u.role==='manager'?'管理者':'成员'}）</option>)}</select></Field>
      <Field label="对象类别"><select value={objectType} onChange={e=>{setObjectType(e.target.value as typeof objectType);setObjectId('')}}><option value="task">任务</option><option value="project_summary">项目摘要</option><option value="scoped_report">已生成的授权报告</option></select></Field><Field label="授权对象"><select required value={objectId} onChange={e=>setObjectId(e.target.value)}><option value="">请选择</option>{objects.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></Field>
      <Field label="历史范围"><select name="historyPolicy" key={`${existing?.id}:${existing?.version}:${subjectId}:${objectId}`} defaultValue={existing?.historyPolicy||'current_onward'}><option value="current_onward">当前状态及授权后的内容</option><option value="all_history">包括全部可授权历史</option></select></Field><label className="checkbox-label"><input type="checkbox" name="capabilities" value="read_evidence" key={`evidence-${existing?.id}:${existing?.version}:${subjectId}:${objectId}`} defaultChecked={existing?.capabilities.includes('read_evidence')}/>同时允许查看证据</label><label className="checkbox-label"><input type="checkbox" name="capabilities" value="export_summary" key={`export-${existing?.id}:${existing?.version}:${subjectId}:${objectId}`} defaultChecked={existing?.capabilities.includes('export_summary')}/>同时允许导出摘要</label><Field label="到期时间（北京时间，可留空）"><input type="datetime-local" name="expiresAt" key={`expiry-${existing?.id}:${existing?.version}:${subjectId}:${objectId}`} defaultValue={existing?.expiresAt?new Date(new Date(existing.expiresAt).getTime()+8*3600000).toISOString().slice(0,16):''}/></Field><Field label="授权原因"><textarea name="reason" required/></Field>{selected&&<p className="note">授权预览：接收人将看到「{selected.title}」当前内容；关联对象仅显示最小引用，其他未授权对象不会自动开放。</p>}
    </Form>
    <details><summary>生成接收人专属摘要</summary><p>仅使用该接收人当前可见的任务事实重新生成。生成后还需在上方授予报告访问；报告授权不能代替来源授权。</p>{reportError&&<p className="error">{reportError}</p>}<Form submitLabel="生成授权范围摘要" onSubmit={async e=>{const f=new FormData(e.currentTarget);const body={subjectId:f.get('subjectId'),title:f.get('title'),taskIds:f.getAll('taskIds'),includeHistory:f.has('includeHistory')};reportAttempt.current=assignmentAttempt(reportAttempt.current,body);try{const report=await api<ScopedReport>('/scoped-reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,requestId:reportAttempt.current.requestId})});reportAttempt.current=null;setReports(old=>[report,...old]);setObjectType('scoped_report');setObjectId(report.id);setSubjectId(report.subjectId);setReportError('')}catch(e){setReportError(e instanceof Error?e.message:'生成失败');throw e}}}><Field label="摘要接收人"><select name="subjectId" required><option value="">请选择</option>{data.users.filter(u=>u.active&&u.role==='observer').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="摘要名称"><input name="title" required/></Field><fieldset><legend>来源任务（必须已授权给接收人）</legend>{data.tasks.map(t=><label className="checkbox-label" key={t.id}><input type="checkbox" name="taskIds" value={t.id}/>{t.title}</label>)}</fieldset><label className="checkbox-label"><input type="checkbox" name="includeHistory"/>包含授权历史事实</label></Form>{reports.map(r=><details key={r.id}><summary>{r.title} · 待授予报告访问</summary><p className="preserve-lines">{r.narrative}</p></details>)}</details>
    <h3>现有授权</h3>{resource.value?.items.map(grant=><article className="collaboration-history" key={`${grant.id}:${grant.version}`}><strong>{nameOf(data,grant.subjectId)} · {data.tasks.find(t=>t.id===grant.objectId)?.title||data.projects.find(p=>p.id===grant.objectId)?.name||grant.objectId}</strong><p>{grant.historyPolicy==='all_history'?'全部历史':'当前及之后'} · {grant.revokedAt?'已撤销':grant.expiresAt?`到期 ${dateTime(grant.expiresAt)}`:'持续有效'}</p><p>{grant.reason}</p>{!grant.revokedAt&&<details><summary>撤销此授权</summary><Form submitLabel="确认撤销对象授权" onSubmit={async e=>{await resource.mutate(`/object-grants/${grant.id}/revoke`,{version:grant.version,reason:new FormData(e.currentTarget).get('reason')},refresh)}}><Field label="撤销原因"><textarea name="reason" required/></Field><p className="form-hint">下次读取立即重新鉴权，含该来源的旧摘要也会拒绝访问。已送达或下载的副本无法追回。</p></Form></details>}</article>)}
  </section>
}
