import { useEffect, useState } from 'react'
import type { NativeCapability, NativeSettingsView, ChannelOperation } from '../../shared/native-actions'
import { api, json, finishSaved } from '../api'
import { Badge, Field, Form, dateTime, type PageProps } from '../ui'
import { useWorkspaceQuery } from '../workspace-query'
import { useDirectoryReferences } from '../directory-references'
import DirectoryAccountPicker, { directoryAccountName } from './DirectoryAccountPicker'
const names: Record<NativeCapability, string> = { identity: '企业成员身份', todo: '原生待办', card: '互动卡片', robot: '机器人指令', orgEvents: '组织事件', leaveSync: '离职补偿同步' }
export default function NativeCapabilities({ data, notify }: PageProps) {
  const [error, setError] = useState(''), [operations, setOperations] = useState<{ links: { id: string; recipientId: string; channel: string; title: string; state: string; lastError: string }[]; operations: ChannelOperation[] } | null>(null)
  const [identityId, setIdentityId] = useState('')
  const scope = `${data.user.id}:${data.user.role}:${data.operationEpoch}:${data.accessScopeVersion}`
  const query = useWorkspaceQuery<NativeSettingsView>('/native/settings', scope, (current, receipt) => receipt && typeof receipt === 'object' && 'settings' in receipt && 'capabilities' in receipt ? receipt as NativeSettingsView : current)
  const view = query.value, people = useDirectoryReferences(operations?.links.map(row => row.recipientId) ?? [], scope)
  const load = async () => { await query.reload() }
  useEffect(() => { setOperations(null); setIdentityId(''); setError('') }, [scope])
  return <section className="notification-settings-card collaboration-settings"><h2>钉钉原生能力</h2><p>按企业权限和客户端验收结果逐项启用。一个业务动作选择一个主通知渠道；结果未知的请求先核对再处理。</p>{error && <p className="error" role="alert">{error}</p>}{query.error && <p className="error" role="alert">状态读取失败：{query.error}<button className="text-button" onClick={() => void load().catch(() => {})}>重新读取状态</button></p>}{query.loading && !view && <p role="status">正在读取原生能力设置…</p>}{view && <>
    <div className="collaboration-native-status">{(Object.keys(names) as NativeCapability[]).map(key => <article key={key}><strong>{names[key]}</strong> <Badge tone={view.capabilities[key].enabled ? 'green' : 'neutral'}>{view.capabilities[key].enabled ? '已启用' : '未启用'}</Badge><p>{view.capabilities[key].reason}</p></article>)}</div>
    <p>事件连接：{view.stream.connected ? '已连接' : '未连接'} · {view.stream.reason} · {view.stream.updatedAt ? dateTime(view.stream.updatedAt) : '无连接记录'}</p>
    <Form key={view.settings.version} submitLabel="保存原生渠道设置" onSubmit={async e => { const f = new FormData(e.currentTarget); await api('/native/settings', json({ version: view.settings.version, ...Object.fromEntries(['todo', 'card', 'robot', 'orgEvents', 'leaveSync'].map(key => [`${key}Enabled`, f.has(`${key}Enabled`)])), fallbackEnabled: f.has('fallbackEnabled'), primaryChannel: f.get('primaryChannel'), pilotUserIds: f.getAll('pilotUserIds'), verifiedCapabilities: f.getAll('verifiedCapabilities'), verificationNote: f.get('verificationNote') }, 'PUT')); notify('原生渠道设置已保存') }}>
      <fieldset><legend>逐项启用</legend>{(['todo', 'card', 'robot', 'orgEvents', 'leaveSync'] as const).map(key => <label className="checkbox-label" key={key}><input name={`${key}Enabled`} type="checkbox" defaultChecked={view.settings[`${key}Enabled`]} disabled={!view.capabilities[key].configured} />{names[key]}</label>)}<label className="checkbox-label"><input name="fallbackEnabled" type="checkbox" defaultChecked={view.settings.fallbackEnabled} />仅在明确未受理时降级为工作通知</label></fieldset>
      <Field label="业务动作主通知渠道"><select name="primaryChannel" defaultValue={view.settings.primaryChannel}><option value="work_notification">工作通知 / 平台详情</option><option value="todo">原生待办</option><option value="card">互动卡片</option></select></Field>
      <fieldset><legend>原生能力试点成员</legend><DirectoryAccountPicker name="pilotUserIds" purpose="notification" multiple defaultSelectedIds={view.settings.pilotUserIds} scope={`${scope}:native:${view.settings.version}`} /></fieldset>
      <fieldset><legend>已完成真实企业验收的能力</legend>{(Object.keys(names) as NativeCapability[]).map(key => <label className="checkbox-label" key={key}><input name="verifiedCapabilities" value={key} type="checkbox" defaultChecked={view.settings.verifiedCapabilities.includes(key)} disabled={!view.capabilities[key].configured} />{names[key]}</label>)}</fieldset><Field label="验收记录"><textarea name="verificationNote" rows={3} defaultValue={view.settings.verificationNote} placeholder="记录验收日期、试点成员、客户端和实际测试结果" /></Field>
    </Form>
    <details><summary>成员身份核验</summary><DirectoryAccountPicker name="identityUserId" purpose="notification" scope={`${scope}:identity`} onChange={ids => setIdentityId(ids[0] ?? '')} />{identityId && <div key={identityId}><p>{view.identities.find(row => row.userId === identityId)?.verified ? '已核验' : view.identities.find(row => row.userId === identityId)?.suspended ? '身份已隔离' : '未核验'}</p><Form submitLabel="核验当前企业身份" onSubmit={async () => { await api(`/native/identities/${encodeURIComponent(identityId)}/verify`, json({})); notify('企业身份已核验'); await finishSaved(load) }}><span /></Form></div>}</details>
    <p>待处理 {view.counts.pending} · 明确失败 {view.counts.failed} · 结果未知 {view.counts.unknown} · 状态不一致 {view.counts.mismatches} · 待处理事件 {view.counts.inboxPending}</p>
    <Form submitLabel="读取渠道处理记录" onSubmit={async () => { setOperations(await api('/native/operations')) }}><span /></Form>
    {operations?.links?.map(link => <article className="collaboration-history" key={link.id}><strong>{link.title}</strong><p>{directoryAccountName(people.get(link.recipientId))} · {link.channel === 'todo' ? '待办' : '互动卡片'} · {link.state}</p>{link.lastError && <p>{link.lastError}</p>}<Form submitLabel="核对平台与钉钉状态" onSubmit={async () => { await api(`/native/links/${link.id}/reconcile`, json({})); await finishSaved(async () => { setOperations(await api('/native/operations')); await load() }) }}><p className="form-hint">核对不会把外部勾选直接解释为平台任务完成。</p></Form>{link.state === 'external_missing' && <Form submitLabel="确认重建缺失的原生事项" onSubmit={async () => { await api(`/native/links/${link.id}/recreate`, json({})); await finishSaved(async () => { setOperations(await api('/native/operations')); await load() }) }}><p className="form-hint">仅在确认原生事项已不存在后重建，并保留旧记录。</p></Form>}</article>)}
  </>}</section>
}
