import { useEffect, useState } from 'react'
import type { TaskDeliveriesView, DeliverySeriesView, DeliverySubmissionView } from '../../shared/deliveries'
import type { Task } from '../../shared/types'
import { api } from '../api'
import { deliveryTiming } from '../delivery-presentation'
import { captureMutationContext } from '../mutation-response'
import { useBusinessResource } from '../use-business-resource'
import { Badge, Field, Form, dateTime, nameOf, type PageProps } from '../ui'
const labels={pending_review:'待验收',accepted:'已通过',returned:'已退回',withdrawn:'已撤回'}
const formValue=(f:FormData,key:string)=>String(f.get(key)||'').trim()
export default function TaskDeliveries({task,data,refresh,readOnly=false}:PageProps&{task:Task;readOnly?:boolean}) {
  const resource=useBusinessResource<TaskDeliveriesView>(`/tasks/${task.id}/deliveries`,`${data.user.id}:${data.operationEpoch}`)
  const [submission,setSubmission]=useState<DeliverySeriesView|'new'|null>(null),[histories,setHistories]=useState<Record<string,{items:DeliverySubmissionView[];nextCursor:string|null}>>({}),[historyError,setHistoryError]=useState('')
  const view=resource.value
  useEffect(()=>{setHistories({});setSubmission(null)},[data.user.id,data.accessScopeVersion])
  async function history(id:string,cursor?:string){try{const context=captureMutationContext();const result=await api<{items:DeliverySubmissionView[];nextCursor:string|null}>(`/delivery-series/${id}/history${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`);if(context!==captureMutationContext())return;setHistories(old=>({...old,[id]:{...result,items:cursor?[...(old[id]?.items||[]),...result.items]:result.items}}));setHistoryError('')}catch(e){setHistoryError(e instanceof Error?e.message:'历史读取失败')}}
  const submit=async(path:string,body:Record<string,unknown>)=>{await resource.mutate(path,body,refresh);setHistories({})}
  return <section className="task-section"><h3>成果交付与验收</h3><p className="form-hint">当周阶段完成、任务自报完成、个人成果通过和月目标验收分别记录。验收操作不会自动改变任务状态。</p>
    {resource.error&&<p className="error">{resource.error}</p>}{resource.loading&&<p>正在读取成果…</p>}{historyError&&<p className="error">{historyError}</p>}
    {view&&!view.items.length&&<p>{task.status==='done'?'历史自报完成，无独立验收记录。':'还没有正式提交的个人成果。'}</p>}
    {view?.items.map(row=><article className="collaboration-history" key={row.series.id}><h4>{row.series.title} <Badge>{labels[row.series.status]}</Badge> <small>当前 v{row.current.delivery.revision}</small></h4><p>{row.current.delivery.actualOutcome}</p><p>验收标准：{row.current.delivery.acceptanceCriteriaSnapshot}</p><p>验收人：{row.reviewerAvailable?nameOf(data,row.series.reviewerId||''):'待指定有效验收人'}</p><p>首次提交 {dateTime(row.firstSubmittedAt)} · 当前提交 {dateTime(row.current.delivery.submittedAt)}</p><p>{row.acceptedAt?`通过版本提交于 ${dateTime(row.acceptedSubmittedAt!)}，验收于 ${dateTime(row.acceptedAt)}；等待 ${Math.max(0,Math.round((Date.parse(row.acceptedAt)-Date.parse(row.acceptedSubmittedAt!))/3600000))} 小时`:'提交及时性与成果质量分别确认，当前质量待确认。'}</p>
      <p>{deliveryTiming(row.current.delivery.submittedAt,row.current.delivery.dueDateSnapshot,row.series.status==='accepted')}</p><p className="form-hint">验收等待时长不计为成员迟交；提交时的期限依据保留在此版本。</p>
      {row.current.delivery.evidenceRefs.map((e,i)=><p key={i}>{/^https?:\/\//.test(e)?<a href={e} target="_blank" rel="noreferrer">{e}</a>:e}</p>)}
      {row.current.effectiveDecision&&<p>当前结论：{labels[row.current.effectiveDecision.conclusion]} · {row.current.effectiveDecision.note} · {dateTime(row.current.effectiveDecision.decidedAt)}</p>}
      {!readOnly&&row.allowedActions.includes('submit')&&<button className="button secondary" onClick={()=>setSubmission(row)}>提交下一版本</button>}
      {!readOnly&&row.allowedActions.includes('review')&&<DecisionForm row={row} action="review" submit={submit}/>}
      {!readOnly&&row.allowedActions.includes('withdraw')&&<DecisionForm row={row} action="withdraw" submit={submit}/>}
      {!readOnly&&row.allowedActions.includes('correct')&&row.current.effectiveDecision&&<DecisionForm row={row} action="correct" submit={submit}/>}
      {!readOnly&&row.allowedActions.includes('reassign')&&<details><summary>重新指派验收人</summary><Form submitLabel="保存重新指派" onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit(`/delivery-series/${row.series.id}/reassign`,{seriesVersion:row.series.version,reviewerId:f.get('reviewerId'),reason:f.get('reason')})}}><Field label="新验收人"><select name="reviewerId" required><option value="">请选择</option>{view.eligibleReviewers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="重新指派原因"><textarea required name="reason"/></Field></Form></details>}
      <button type="button" className="text-button" onClick={()=>void history(row.series.id)}>查看全部提交与决定</button>
      {histories[row.series.id]?.items.map(item=><details key={item.delivery.id}><summary>v{item.delivery.revision} · {dateTime(item.delivery.submittedAt)}{item.effectiveDecision?` · ${labels[item.effectiveDecision.conclusion]}`:''}</summary><p>{item.delivery.actualOutcome}</p><p>验收标准：{item.delivery.acceptanceCriteriaSnapshot}</p>{item.decisions.map(d=><p key={d.id}>{labels[d.conclusion]} · {d.note} · {dateTime(d.decidedAt)}{d.supersedesDecisionId?'（更正前一决定，原记录保留）':''}</p>)}{!readOnly&&row.allowedActions.includes('correct')&&item.effectiveDecision&&item.delivery.id!==row.current.delivery.id&&<DecisionForm row={{...row,current:item}} action="correct" submit={submit}/>}</details>)}
      {histories[row.series.id]?.nextCursor&&<button type="button" className="text-button" onClick={()=>void history(row.series.id,histories[row.series.id].nextCursor!)}>加载更早版本</button>}
    </article>)}
    {!readOnly&&view?.canSubmit&&<button className="button secondary" onClick={()=>setSubmission('new')}>{view.items.length?'新增独立交付项':'正式提交成果'}</button>}
    {submission&&view&&!readOnly&&<Form key={submission==='new'?'new':submission.series.id} submitLabel="正式提交验收" draftKey={`task-delivery:${data.user.id}:${task.id}:${submission==='new'?'new':submission.series.id}:v${task.version}`} onCancel={()=>setSubmission(null)} onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit(`/tasks/${task.id}/deliveries`,{taskVersion:task.version,previousRevision:submission==='new'?0:submission.current.delivery.revision,...(submission==='new'?(view.items.length?{newSeries:true,title:f.get('title')}:{title:f.get('title')}):{seriesId:submission.series.id,seriesVersion:submission.series.version,previousSubmissionId:submission.current.delivery.id}),actualOutcome:formValue(f,'actualOutcome'),evidenceRefs:formValue(f,'evidenceRefs').split('\n').map(v=>v.trim()).filter(Boolean),acceptanceCriteria:formValue(f,'acceptanceCriteria'),reviewerId:f.get('reviewerId')||null,proxyReason:formValue(f,'proxyReason'),replaceAccepted:f.has('replaceAccepted'),markTaskDone:f.has('markTaskDone'),completionNote:formValue(f,'actualOutcome')});setSubmission(null)}}>
      {submission==='new'&&<Field label="交付项名称"><input name="title" required defaultValue={view.items.length?'':task.title}/></Field>}<Field label="成果说明"><textarea name="actualOutcome" required rows={4}/></Field><Field label="验收标准"><textarea name="acceptanceCriteria" required rows={3} defaultValue={submission==='new'?task.requestedOutcome||'':submission.current.delivery.acceptanceCriteriaSnapshot}/></Field><Field label="证据链接或文字证据（每行一项）"><textarea name="evidenceRefs" rows={3}/></Field><Field label="验收人"><select name="reviewerId" required={view.eligibleReviewers.length>0} defaultValue={submission==='new'?'':submission.series.reviewerId||''}><option value="">{view.eligibleReviewers.length?'请选择非本人管理者':'暂无合资格验收人，提交后等待指派'}</option>{view.eligibleReviewers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field>
      {task.ownerId!==data.user.id&&<Field label="代交原因"><textarea required name="proxyReason"/></Field>}{submission!=='new'&&submission.series.status==='accepted'&&<label className="checkbox-label"><input type="checkbox" required name="replaceAccepted"/>本次成果明确替代原已通过版本，重新等待验收</label>}{task.status!=='done'&&<label className="checkbox-label"><input type="checkbox" name="markTaskDone"/>同时标记整个任务自报完成（成果说明用作完成说明）</label>}
    </Form>}
  </section>
}
function DecisionForm({row,action,submit}:{row:DeliverySeriesView;action:'review'|'withdraw'|'correct';submit:(path:string,body:Record<string,unknown>)=>Promise<void>}) {
  const label=action==='review'?'验收当前成果':action==='withdraw'?'撤回当前提交':'更正此版本的有效决定'
  return <details><summary>{label}</summary><Form submitLabel={label} onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit(`/deliveries/${row.current.delivery.id}/decisions`,{seriesVersion:row.series.version,action,...(action==='withdraw'?{}:{conclusion:f.get('conclusion')}),note:f.get('note'),...(action==='correct'?{supersedesDecisionId:row.current.effectiveDecision!.id}:{})})}}>{action!=='withdraw'&&<Field label="验收结论"><select name="conclusion"><option value="accepted">通过</option><option value="returned">退回返工</option></select></Field>}<Field label={action==='review'?'验收结论或退回原因':'操作原因'}><textarea name="note" required rows={3}/></Field>{action==='correct'&&<p className="form-hint">保留原决定和原验收时间；更正历史版本不改变当前新版本状态。</p>}</Form></details>
}
