import { useEffect, useState } from 'react'
import DirectoryAccountPicker, { directoryAccountName } from './DirectoryAccountPicker'
import { useDirectoryReferences } from '../directory-references'
import type { BlockerView, TaskSupportView } from '../../shared/support'
import type { Task } from '../../shared/types'
import { useBusinessResource } from '../use-business-resource'
import { Badge, Field, Form, Modal, dateTime, type PageProps } from '../ui'
const stateNames:Record<string,string>={unassigned:'待分派',awaiting_response:'待回应',in_progress:'处理中',responded:'已回应',management_closed:'管理关闭'}
const utc=(value:FormDataEntryValue|null)=>value?new Date(`${value}:00+08:00`).toISOString():undefined
type Submit=(path:string,body:Record<string,unknown>)=>Promise<void>
export default function TaskSupport({task,data,refresh,readOnly=false}:PageProps&{task:Task;readOnly?:boolean}) {
  const resource=useBusinessResource<TaskSupportView>(`/tasks/${task.id}/support`,`${data.user.id}:${data.operationEpoch}:${data.accessScopeVersion||''}`),view=resource.value
  const [create,setCreate]=useState(false)
  const scope=`${data.user.id}:${data.user.role}:${data.operationEpoch}:${data.accessScopeVersion||''}`
  const people=useDirectoryReferences(view?.decisions.map(row=>row.decisionOwnerId)??[],scope,'assignment')
  useEffect(()=>setCreate(false),[scope])
  const submit:Submit=(path,body)=>resource.mutate(path,body,refresh)
  return <section className="task-section"><h3>支持与决策</h3><p className="form-hint">协调回应和管理关闭分别留痕。管理关闭不解除技术阻塞；执行人仍需更新实际工作状态。</p>{resource.error&&<p className="error">{resource.error}</p>}{resource.loading&&<p>正在读取支持事项…</p>}
    {view&&!view.blockers.length&&<p>尚未纳入支持流程。</p>}
    {!readOnly&&view?.canEnrollBlocker&&<Form submitLabel="确认将当前阻塞纳入支持流程" onSubmit={()=>submit(`/tasks/${task.id}/blockers`,{taskVersion:task.version})}><p>历史发生时间不明的阻塞会如实标记，不补造时间。</p></Form>}
    {view?.blockers.map(row=><BlockerCard key={row.episode.id} row={row} data={data} submit={submit} readOnly={readOnly}/>)}
    <h3>决策事项</h3>{view&&!view.decisions.length&&<p>暂无正式决策事项。</p>}
    {view?.decisions.map(row=><article className="collaboration-history" key={row.id}><h4>{row.question} <Badge>{row.status==='open'?'待决策':row.status==='decided'?'已决策':'已取消'}</Badge></h4><p>责任人：{directoryAccountName(people.get(row.decisionOwnerId))}{!row.ownerAvailable?'（账号失效，待重派）':''} · 期限 {dateTime(row.responseDueAt)}</p>{!!row.options.length&&<ul>{row.options.map((option,index)=><li key={index}>{option}</li>)}</ul>}{row.result&&<p>决定：{row.result} · {row.decidedAt&&dateTime(row.decidedAt)}</p>}
      {!readOnly&&row.allowedActions.includes('decide')&&<Form submitLabel="记录决策结果" onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit(`/decision-requests/${row.id}/decide`,{version:row.version,result:f.get('result')})}}><Field label="明确决策结果"><textarea name="result" required rows={3}/></Field></Form>}
      {!readOnly&&row.allowedActions.includes('reassign')&&<details><summary>重新指派决策责任人</summary><Form submitLabel="保存决策指派" onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit(`/decision-requests/${row.id}/reassign`,{version:row.version,decisionOwnerId:f.get('decisionOwnerId'),responseDueAt:utc(f.get('responseDueAt')),reason:f.get('reason')})}}><PeopleField label="决策责任人" name="decisionOwnerId" scope={scope} managerOnly/><Field label="回应期限（北京时间）"><input name="responseDueAt" type="datetime-local" required/></Field><Field label="调整原因"><textarea name="reason" required/></Field></Form></details>}
      {!readOnly&&(['cancel','reopen'] as const).filter(action=>row.allowedActions.includes(action)).map(action=><details key={action}><summary>{action==='cancel'?'取消决策事项':'重新开启决策'}</summary><Form submitLabel={action==='cancel'?'确认取消':'开启新的决策代次'} onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit(`/decision-requests/${row.id}/${action}`,{version:row.version,reason:f.get('reason'),...(action==='reopen'?{decisionOwnerId:f.get('decisionOwnerId'),responseDueAt:utc(f.get('responseDueAt'))}:{})})}}><Field label="原因"><textarea name="reason" required/></Field>{action==='reopen'&&<><PeopleField label="决策责任人" name="decisionOwnerId" scope={scope} managerOnly/><Field label="新的回应期限（北京时间）"><input name="responseDueAt" type="datetime-local" required/></Field></>}</Form></details>)}
    </article>)}
    {!readOnly&&view?.canCreateDecision&&<button type="button" className="button secondary" onClick={()=>setCreate(true)}>{task.decisionNeeded?'将需决策原文转为决策事项':'新建决策事项'}</button>}
    {create&&view&&!readOnly&&<Form submitLabel="创建决策事项" draftKey={`task-decision:${data.user.id}:${task.id}:v${task.version}`} onCancel={()=>setCreate(false)} onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit('/decision-requests',{taskId:task.id,taskVersion:task.version,question:f.get('question'),options:String(f.get('options')||'').split('\n').map(s=>s.trim()).filter(Boolean),decisionOwnerId:f.get('decisionOwnerId'),responseDueAt:utc(f.get('responseDueAt')),...(f.get('blockerEpisodeId')?{blockerEpisodeId:f.get('blockerEpisodeId')}:{})});setCreate(false)}}><Field label="需要决定的问题"><textarea name="question" required rows={3} defaultValue={task.decisionNeeded||''}/></Field><Field label="候选方案（每行一个）"><textarea name="options" rows={3}/></Field><PeopleField label="决策责任人" name="decisionOwnerId" scope={scope} managerOnly/><Field label="回应期限（北京时间）"><input name="responseDueAt" type="datetime-local" required/></Field><Field label="关联阻塞（选填）"><select name="blockerEpisodeId"><option value="">不关联</option>{view.blockers.map(row=><option key={row.episode.id} value={row.episode.id}>{row.episode.reason}</option>)}</select></Field></Form>}
  </section>
}
function PeopleField({label,name,scope,managerOnly=false}:{label:string;name:string;scope:string;managerOnly?:boolean}) {return <div className="field"><span>{label}</span><DirectoryAccountPicker name={name} scope={scope} role={managerOnly?'manager':'business'} label="搜索明确的责任人" /></div>}
function BlockerCard({row,data,submit,readOnly=false}:{row:BlockerView;data:PageProps['data'];submit:Submit;readOnly?:boolean}) {
  const episode=row.episode
  const scope=`${data.user.id}:${data.user.role}:${data.operationEpoch}:${data.accessScopeVersion||''}`
  const people=useDirectoryReferences(episode.coordinatorId?[episode.coordinatorId]:[],scope,'assignment')
  const available=row.allowedActions.filter(action=>['record','respond','defer','close'].includes(action))
  return <article className="collaboration-history"><h4>{row.task.title} <Badge>{stateNames[episode.coordinationState||'unassigned']}</Badge> <Badge>{episode.resolvedAt?'技术阻塞已解除':'技术阻塞未解除'}</Badge></h4><p>{episode.reason}</p><p>{episode.openedAtKnown===false?'历史实际发生时间不明':`发生于 ${dateTime(episode.openedAt)}`}</p><p>影响：{episode.impact||'未填写'}</p><p>诉求：{episode.supportNeeded||'未填写'}</p><p>协调人：{episode.coordinatorId?directoryAccountName(people.get(episode.coordinatorId)):'待分派'}{!row.coordinatorAvailable&&episode.coordinatorId?'（待重新指派）':''}{episode.responseDueAt?` · 回应期限 ${dateTime(episode.responseDueAt)}`:''}</p>{episode.responseNote&&<p>回应：{episode.responseNote}</p>}{episode.reviewAt&&<p>约定复查：{dateTime(episode.reviewAt)}</p>}{row.minimalContext&&<p className="form-hint">你被指定处理此支持事项，此处展示完成协调所需的最小上下文。</p>}
    {!readOnly&&row.allowedActions.includes('assign')&&<details><summary>指派 / 转派协调人</summary><Form submitLabel="保存协调责任" onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit(`/blockers/${episode.id}/assign`,{version:episode.version,coordinatorId:f.get('coordinatorId'),responseDueAt:utc(f.get('responseDueAt')),reason:f.get('reason')})}}><PeopleField label="协调人" name="coordinatorId" scope={scope}/><Field label="回应期限（北京时间）"><input type="datetime-local" name="responseDueAt" required/></Field><Field label="指派原因"><textarea name="reason" required/></Field></Form></details>}
    {!readOnly&&available.length>0&&<Form submitLabel="保存支持回应" draftKey={`blocker-response:${data.user.id}:${episode.id}:v${episode.version}`} onSubmit={async e=>{const f=new FormData(e.currentTarget);await submit(`/blockers/${episode.id}/handle`,{version:episode.version,action:f.get('action'),note:f.get('note'),reviewAt:utc(f.get('reviewAt'))})}}><Field label="处理方式"><select name="action">{available.map(action=><option key={action} value={action}>{{record:'记录处理进度',respond:'正式回应',defer:'接受延期复查',close:'管理关闭支持事项'}[action]}</option>)}</select></Field><Field label="处理说明"><textarea name="note" required rows={3}/></Field><Field label="建议 / 接受的复查日期（北京时间）"><input type="datetime-local" name="reviewAt"/></Field></Form>}
    <details><summary>责任与回应历史（{row.actions.length}）</summary>{row.actions.map(action=><p key={action.id}>{dateTime(action.createdAt)} · {action.note}</p>)}</details>
  </article>
}
export function MinimalSupportPanel({blockerId,onClose,...props}:PageProps&{blockerId:string;onClose:()=>void}) {
  const resource=useBusinessResource<BlockerView>(`/blockers/${encodeURIComponent(blockerId)}`,`${props.data.user.id}:${props.data.user.role}:${props.data.operationEpoch}:${props.data.accessScopeVersion||''}`)
  return <Modal wide title="支持事项" onClose={onClose}>{resource.error&&<p className="error">{resource.error}</p>}{resource.value?<BlockerCard key={resource.value.episode.id} row={resource.value} data={props.data} submit={(url,body)=>resource.mutate(url,body,props.refresh)}/>:!resource.error&&<p>正在读取被指派的支持事项…</p>}</Modal>
}
